
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 465;
const int acc_off_y = -24;
const int acc_off_z = -5515;
const float acc_scale_x = 16357.019421;
const float acc_scale_y = 17635.673230;
const float acc_scale_z = 22268.702858;

const int magn_off_x = -161;
const int magn_off_y = -32;
const int magn_off_z = -101;
const float magn_scale_x = 289.807350;
const float magn_scale_y = 271.704769;
const float magn_scale_z = 223.227055;
